name: CI Docker Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Eliminar contenedor previo (si existe)
        run: docker rm -f app || true

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        run: docker build -t prueba-api .

      - name: Ejecutar contenedor en segundo plano
        run: docker run -d -p 5001:5000 --name app prueba-api

      - name: Esperar a que arranque la API
        run: sleep 5

      - name: Ejecutar pruebas unitarias
        run: docker exec app pytest test/test_operaciones.py

      - name: Ejecutar pruebas de integración
        run: docker exec app pytest test/test_integracion.py

      - name: Ejecutar pruebas funcionales
        run: docker exec app pytest test/test_funcional.py

      - name: Detener contenedor
        run: docker stop app
